---
# defaults file for kvm_provision
base_image_name: Fedora-Cloud-Base-35-1.2.x86_64.qcow2
base_image_url: https://mirrors.xtom.de/fedora/releases/35/Cloud/x86_64/images/{{ base_image_name }}
base_image_sha: fe84502779b3477284a8d4c86731f642ca10dd3984d2b5eccdf82630a9ca2de6
libvirt_pool_dir: "/home/darthv/libvirt/images"
vm_name: f34-dev
vm_vcpus: 2
vm_ram_mb: 2048
vm_net: default
vm_root_pass: 
cleanup_tmp: no
ssh_key: $HOME/.ssh/id_rsa.pub
