---
- hosts: rpi 
  become: yes
  #remote_user: root
  tasks:
  - name: Delete arkade and k3sub
    file:
      path: "{{ item }}"
      state: absent
    with_items: 
      - /usr/local/bin/arkade
      - /usr/local/bin/k3sup

  - name: Check k3s is installed
    stat:
      path: /usr/local/bin/k3s-uninstall.sh
    register: k3s

  - name: Check k3s agent is installed
    stat:
      path: /usr/local/bin/k3s-agent-uninstall.sh
    register: k3sagent

  - debug: msg="Path exists and is a directory"
    when: k3s.stat.exist is defined and k3sagent.stat.exist

  - name: Delete k3s 
    shell: /usr/local/bin/k3s-uninstall.sh
    when: k3s.stat.exist is defined


  - name: Delete k3s agent
    shell: /usr/local/bin/k3s-agent-uninstall.sh 
    when: k3sagent.stat.exist is defined

  - name: Install ntpdate
    ansible.builtin.package:
      name: kubernetes-client
      state: absent
