---
- hosts: rpi3 
  #become: yes
  remote_user: user
  tasks:
  - name: Install k3s
    shell: |
      curl -sfL https://get.k3s.io | sudo sh -
      sudo systemctl status k3s
      sudo cat /var/lib/rancher/k3s/server/node-token

  - name: Install k3sup
    shell: |
      curl -sLS https://get.k3sup.dev | sudo sh
    #ignore_errors: yes 

  - name: Install arkade 
    shell: |
      curl -sLS https://dl.get-arkade.dev | sudo sh
    #ignore_errors: yes


  - name: Join Workers
    shell: |
      k3sup install --ip 192.168.33 --user user
      k3sup join --ip "{{ item }}" --server-ip 192.168.1.33 --user user
    with_items:
      - 192.168.1.4 
      - 192.168.1.32

- hosts: rpi 
  become: yes
  tasks:
  - name: Install kubernetes-client
    ansible.builtin.package:
      name: kubernetes-client
      state: present

